import NavBar from "@/components/Navbar/Index";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Mahou Reader",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className='bg-base-100 text-base-content'>
        <NavBar />
        {children}
      </body>
    </html>
  );
}